import * as tmp from "tmp";
import * as fs from "node:fs/promises";
import * as util from "node:util";
import * as path from "node:path";
import * as child_process from "node:child_process";
import type { RenderContext } from "./types";

const execFile = util.promisify(child_process.execFile);

/**
 * Process and render a single module to STL
 */
export async function processModule(moduleName: string, ctx: RenderContext): Promise<void> {
    // Generate temp file contents
    const tempPath = tmp.tmpNameSync({ postfix: ".scad" });
    const tempFileContents = `// Generated by scadr\nuse <${ctx.fullPath}>\n${moduleName}();`;
    // Write out the temp file
    await fs.writeFile(tempPath, tempFileContents, { encoding: "utf-8" });

    let outFile: string;
    if (ctx.options.zip && ctx.tempDir) {
        // In zip mode, put STL files in temp directory without prefix
        outFile = path.join(ctx.tempDir, `${moduleName}.stl`);
    } else {
        // Normal mode with prefix
        outFile = `${ctx.filePath.replace(/\.scad/i, `-${moduleName}.stl`)}`;
    }
    
    const args = getArgs(tempPath, outFile, ctx);
    if (ctx.options.dry) {
        console.log(`${ctx.ospath} ${args.join(" ")}`);
    } else {
        await execFile(ctx.ospath, args);
        if (ctx.options.zip) {
            ctx.stlFiles.push(outFile);
        }
    }
    await fs.unlink(tempPath);
}

function getArgs(inputFile: string, outFile: string, ctx: RenderContext): string[] {
    const opts = [
        `--o`, outFile,
        `--export-format`, 'binstl'
    ];
    if (ctx.supportsBackend) {
        opts.push('--backend', 'manifold');
    }
    for (const def of ctx.options.define) {
        opts.push('--D', def);
    }
    opts.push(inputFile);
    return opts;
}
